# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  test:
    docker:
    # specify the version you desire here
    #
    # all images and tags here:
    #   https://circleci.com/docs/2.0/docker-image-tags.json
    #
    - image: circleci/node:12.1-stretch

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: rm -rf node_modules/loader && npm install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: Compile Typescript
        command: npx tsc

    - run:
        name: npm test
        command: npm test

workflows:
  version: 2
  parallel_workflow:
    jobs:
      - build

